# -*- coding: utf-8 -*-
"""klaster.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BP3brJCvkKIjX4MAau75WLc56fFONFfN
"""

import pandas as pd
df = pd.DataFrame({
    'x':[41, 36, 32, 34, 32, 31, 24, 30, 45, 52, 51, 52, 55, 53, 55, 61, 64, 69, 72],
    'y':[39, 36, 30, 52, 54, 46, 55, 59, 63, 70, 66, 63, 58, 23, 30, 30, 31, 32, 29]
    })
df.head()

import matplotlib.pyplot as plt
fig=plt.figure(figsize=(5,5))
plt.scatter(df['x'], df['y'], alpha=0.8, edgecolor='k', cmap='virdis')

from sklearn.cluster import AgglomerativeClustering
clustering = AgglomerativeClustering(n_clusters=5, linkage='complete')
clusterku=clustering.fit(df)
print(clustering.labels_)

import scipy.cluster.hierarchy as sch
from scipy.cluster.hierarchy import dendrogram
dendrogram = sch.dendrogram(sch.linkage(df, method ='ward'))
plt.title('Dendogram')
plt.xlabel('Index ke-')
plt.ylabel('Eculidean distances')
plt.show