# -*- coding: utf-8 -*-
"""tugasP3_2010511051.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hhQVKnEVmkNrU4x_3jHSqs1ME9-NNNZ6
"""

import pandas as pd
# File CSV
csv_path ="https://archive.ics.uci.edu/ml/machine-learning-databases/hepatitis/hepatitis.data"
# memberi nama kolom
headers=["Class", "AGE", "SEX", "STEROID", "ANTIVIRALS","FATIGUE","MALAISE","ANOREXIA","LIVER BIG","LIVER FIRM","SPLEEN PALPABLE","SPLIDERS","ACITES","VARICES","BILIRUBIN","ALK PHOSPHATE","SGOT","ALBUMIN","PROTIME","HISTOLOGY"]
df_csv = pd.read_csv(csv_path)
df_csv.columns=headers
df_csv.head()

#menyimpan ke dalam CSV
df_csv.to_csv("CSV1.csv", index=False)

#menampilkan sepuluh data teratas
x = df_csv.iloc[0:10]
x

# menampilkan sepuluh data terakhir
x = df_csv.iloc[len(df_csv)-10:]
x

# mengakses kolom class hingga fatigue
x = df_csv.iloc[:,0:6]
x

# menampilkan kolom Class dan 4 kolom lainnya secara random
import numpy as np
x = df_csv.set_index('Class').sample(4, axis=1).reset_index()
x