# -*- coding: utf-8 -*-
"""B_2010511051_Riandra Putra P_No_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EKb5zz85WLVQZw6lSEjsXHaqJAOEQvaL

Nama : Riandra Putra Pratama

Nim : 2010511051

Kelas : Praktikum Data Mining dan Data Warehouse - B
"""

import pandas as pd

df = pd.read_csv('sample_data/hepc.csv')
df.head(5)

dataclustering= df[["Age", "Sex", "ALB", "ALP", "ALT", "AST", "BIL", "CHE", "CHOL", "CREA", "GGT", "PROT"]]

from sklearn.cluster import KMeans
from sklearn import metrics
kmeans = KMeans(n_clusters=6,random_state=1).fit(dataclustering)
label=kmeans.labels_
centroid = kmeans.cluster_centers_
label
print(metrics.calinski_harabasz_score(dataclustering, label))