# -*- coding: utf-8 -*-
"""B_2010511051_Riandra Putra P_No_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WTjqJopEm6KGCR2dgC8jDomt8WUvPISG

Nama : Riandra Putra Pratama

Nim : 2010511051

Kelas : Praktikum Data Mining dan Data Warehouse - B
"""

pip install efficient-apriori

from efficient_apriori import apriori

import csv

with open('sample_data/app_data.csv', newline='') as f:
    reader = csv.reader(f)
    data = list(reader)

print(data)

itemsets, rules= apriori(data, min_support=0.75, min_confidence=0.9)

for j in range(1, len(itemsets)+1):
  print(itemsets)
  print("\n")

for i in range(len(rules)):
  print(rules[i])
  print()