# -*- coding: utf-8 -*-
"""evaluasicluster2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1reCWcwmlcUeeBTX-DxrpDZk0ZzPvp4F6
"""

import pandas as pd
csv_path ="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
headers=["sepal_length", "sepal_width", "petal_length", "petal_width", "class_label"]
datairis = pd.read_csv(csv_path, names=headers)
datairis.head()

#megambilvariable untuk clustering
dataclustering= datairis[["sepal_length", "sepal_width", "petal_length", "petal_width"]]

from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=3)
kmeans.fit(dataclustering)
label=kmeans.labels_
centroid = kmeans.cluster_centers_
label

from sklearn import metrics
label_asli=datairis['class_label']
label_prediksi=label
FMI=metrics.fowlkes_mallows_score(label_asli, label_prediksi)
print("FMI= ", FMI)