# -*- coding: utf-8 -*-
"""evaluasicluster1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10H6MityFtE-DDofM1ARNqrvMCShNAeDW
"""

import pandas as pd
from sklearn.cluster import KMeans
df = pd.DataFrame({
        'x':[41, 36, 32, 34, 32, 31, 24, 30, 45, 52, 51, 52, 55, 53, 55, 61, 64, 69, 72],
        'y':[39, 36, 30, 52, 54, 46, 55, 59, 63, 70, 66, 63, 58, 23, 30, 30, 31, 32, 29]
        })
df.head()

kmeans = KMeans(n_clusters=2)
kmeans.fit(df)
label=kmeans.labels_
centroid = kmeans.cluster_centers_

import matplotlib.pyplot as plt
fig = plt.figure(figsize=(5, 5))

plt.scatter(df['x'],df['y'], c=label, alpha=0.8, edgecolor='k', cmap='viridis')
for idx, centroid in enumerate(centroid):
    plt.scatter(*centroid, c="red")
plt.xlim(0,80)
plt.ylim(0,80)
plt.show()

from sklearn import metrics
CHIndex=metrics.calinski_harabasz_score(df, label)
print(CHIndex)

for i in range(2,8):
  kmeans=KMeans(n_clusters=i)
  kmeans.fit(df)
  label=kmeans.labels_
  CHIndex=metrics.calinski_harabasz_score(df, label)
  print("ch index untuk k = ", i, "=", CHIndex)