# -*- coding: utf-8 -*-
"""gaussian.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H1GrA6zxtoGvqTXYMNpGcseqKgnimzV-
"""

import pandas as pd
csv_path='https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
headers=['sepal_lenght', 'sepal_width', 'petal_lenght', 'petal_width', 'class_label']
datairis= pd.read_csv(csv_path, names=headers)
datairis.head()

import numpy as np
x = np.array(datairis[["sepal_lenght","sepal_width","petal_lenght","petal_width"]])
y=np.array(datairis["class_label"])

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size =0.2, random_state=0, stratify=y )

from sklearn.naive_bayes import GaussianNB
model_gnb= GaussianNB()

model_gnb.fit(X_train, y_train)

prediksi = model_gnb.predict(X_test)
print(prediksi)

print(y_test)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,prediksi)

from sklearn.metrics import classification_report
print(classification_report(y_test, prediksi, target_names=['Iris-setosa', 'Iris-versicolor','Iris-virginica' ]))