# -*- coding: utf-8 -*-
"""tugas_P13_2010511051.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VX5D2_bwjYuT-qJGWW2_gKZMKkWPS8ks

Nama : Riandra Putra Pratama
Nim : 2010511051
"""

#CONNECT GOOGLE DRIVE
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd

df = pd.read_csv("/content/drive/My Drive/Dataset/nilai_mhs_real.csv", names=["nilai1", "nilai2", "nilai3", "nilai4"])
df.head(5)

from sklearn.cluster import KMeans
cluster3=KMeans(n_clusters=3)
cluster3.fit(df[['nilai1', 'nilai3']])
labels3=cluster3.predict(df[['nilai1', 'nilai3']])
labels3

centroids3=cluster3.cluster_centers_ 
jml_iter=cluster3.n_iter_
jml_iter
#Run Program ini, misal 10 kali dan amati perubahannya. apakah jml iterasi dan labelnya selalu sama?
# -> akan selalu berbeda setiap kali di running

import matplotlib.pyplot as plt
fig=plt.figure(figsize=(5,5))
plt.scatter(df['nilai1'], df['nilai3'], c=labels3, alpha=0.5, edgecolor='k', cmap='viridis')
for idx, centroid in enumerate(centroids3):
  plt.scatter(*centroid, c='red')
  plt.xlim(0,100)
  plt.ylim(0,100)
  plt.show